### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by Nuruddin999** [EdouardCourty/user-instagram#11]
Hello ! 
when i want to run `userInstagram.getPostData("CEGskglng0A")
      .then(console.log)
      .catch(console.error)`
it throws ` UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
    at ...\node_modules\user-instagram\src\scrape.js:113:68`

**Comment by EdouardCourty** [comment]
Hey, thanks for the feedback ! I'm fixing this right now.

**Comment by EdouardCourty** [comment]
Published an update, it should work properly now.
