### ISSUE TITLE
Refused to set unsafe header 'user-agent' & CORS cache-control rejection

### ISSUE THREAD

**Issue by dylanmcgowan** [EdouardCourty/user-instagram#16]
As of version `2.1.3` this package is broken and unusable. It works as intended on version `2.0.8` but you changed the request headers after that version which is causing the breaking bug.

You are setting an unsafe header 'user-agent' causing this error : `Refused to set unsafe header "user-agent"`

And there's also an invalid field `cache control` that returns the following error.

`Access to XMLHttpRequest at 'https://www.instagram.com/xyz/?__a=1' from origin 'https://www.mysite.com' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.`

Can you please revert things to how they were or remove the new request parameters?

**Comment by EdouardCourty** [comment]
Hello, thanks for your comment. I'll investigate on this tomorrow morning and will fix it ASAP.
Sorry for the time loss !

**Comment by EdouardCourty** [comment]
Hi again, I checked the code and nothing fails when I run my tests.
Could you please copy and paste the exact piece of code that throws the error ?

**Comment by kellvembarbosa** [comment]
Hi @EdouardCourty  Thanks for plugin is best solution for me, I have the same problem of CORS 

is here error in my console: 

`Access to XMLHttpRequest at 'https://www.instagram.com/hgs_samuel/?__a=1' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authority is not allowed by Access-Control-Allow-Headers in preflight response.
Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:83)
Promise.catch (async)
_callee$ @ index.tsx?8b04:10
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
_initData @ index.tsx?8b04:7
initData @ index.tsx?8b04:7
eval @ index.tsx?8b04:16
invokePassiveEffectCreate @ react-dom.development.js?61bb:23487
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23574
unstable_runWithPriority @ scheduler.development.js?3069:646
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
performSyncWorkOnRoot @ react-dom.development.js?61bb:22269
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:646
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
flushPassiveEffectsImpl @ react-dom.development.js?61bb:23620
unstable_runWithPriority @ scheduler.development.js?3069:646
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushPassiveEffects @ react-dom.development.js?61bb:23447
eval @ react-dom.development.js?61bb:23324
workLoop @ scheduler.development.js?3069:590
flushWork @ scheduler.development.js?3069:545
performWorkUntilDeadline @ scheduler.development.js?3069:157
Show 3 more frames from Library code
xhr.js?b50d:178 GET https://www.instagram.com/hgs_samuel/?__a=1 net::ERR_FAILED`

**Comment by EdouardCourty** [comment]
I removed the headers in 2.1.6, please update !
You're the first one to report this issue, but the module works without these headers, so here we go :)
Have a great day !
