### ISSUE TITLE
429 response code 

### ISSUE THREAD

**Issue by shrenik9** [EdouardCourty/user-instagram#20]
This Package working smoothly until last week. but right now I'm getting 429 error code. does Instagram change anything?

**Comment by EdouardCourty** [comment]
Hello, I'm checking it right now. Thanks for the feedback !

**Comment by EdouardCourty** [comment]
Are you sending a lot of requests ?
All of my tests run smoothly, I don't see any error or 429 code.

HTTP 429 means "Too many requests", I guess if you spam the same endpoint you get ratel-imited for a while.

Try to reduce the number of requests you send !

**Comment by shrenik9** [comment]
I'm using this package in my react native app and it was working nice but suddenly came this error code from last week and I'm not sending too many requests. Instagram redirect to the login page.

**Comment by EdouardCourty** [comment]
Do you have it everytime you fetch a user / post or randomly ?

**Comment by shrenik9** [comment]
I'm fetching specific public profile users and as I said it was working fine until last week. I have to check my code maybe I did something wrong or what.

**Comment by EdouardCourty** [comment]
I can't really help you on this since you're the only one that has this error + I don't have the code. This let me think something in your program is wrong. Update when you have news !

**Comment by shrenik9** [comment]
sure bro
