### ISSUE TITLE
UnableToFetchPostDataError when using AWS

### ISSUE THREAD

**Issue by lixuanle** [EdouardCourty/user-instagram#21]
Hi, first of all thanks for all you've done on this it's really been a big help.

I'm running into a problem where when I try to use this package in my app locally, theres no problem but when I deploy my app to AWS I keep running into this issue where the scrapper is unable to find the post and I'm getting:

`UnableToFetchPostDataError: An error occured while fetching post data for shortcode CIyq3yGD5Pd. Maybe this post does not exist ?`

Any ideas why?

**Comment by EdouardCourty** [comment]
Hello, a lot of users have running into this case when using AWS. It seems like Instagram doesn't like to get scrapped from AWS machines, like if they put an IP-filter...

I though about some workarounds but if the blocking really works with IP ranges, I don't really know what to do.
Using a proxy is way too tryhard for this type of things, and not very user-friendly...
