### ISSUE TITLE
UnableToFetchUserDataError

### ISSUE THREAD

**Issue by LWJerri** [EdouardCourty/user-instagram#22]
Hello! When I try to get information about the user, I'm getting the error.

```
UnableToFetchUserDataError: An error occured while fetching data for user lwjerri. Maybe this user does not exist ?
    at Function.fromUsername (C:\Users\Andrey\Desktop\jobs\japi\node_modules\user-instagram\src\Exceptions\UnableToFetchUserDataError.js:7:12)
    at C:\Users\Andrey\Desktop\jobs\japi\node_modules\user-instagram\src\scrape.js:67:43
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by EdouardCourty** [comment]
Hello, what is the username you're fetching ?

**Comment by EdouardCourty** [comment]
Hello. I identified the issue and will be fixing it asap. Sorry for the inconvenience !

**Comment by EdouardCourty** [comment]
It happens that Instagram likes to send 429 HTTP Codes sometimes to user, which is caugth by the code and interpreted as the error you saw: `UnableToFetchUserDataError`

I'm going to create another message or error for this type of case.

**Comment by LWJerri** [comment]
> Are you sending a lot of requests ?

1 per 20 seconds.

> I'm going to create another message or error for this type of case.

Okay, thanks for your response!

**Comment by LWJerri** [comment]
Can you bypass 429 error?

**Comment by EdouardCourty** [comment]
Hi again, unfortunately the 429 HTTP Code is send by Instagram when you send too many requests.
Maybe try to lower your request rate, or use a proxy that changes your IP address regularly.

There is no real way to bypass this since it's kind of an IP-blocking system they have, to avoid getting scrapped.

**Comment by LWJerri** [comment]
> Hi again, unfortunately the 429 HTTP Code is send by Instagram when you send too many requests.
> Maybe try to lower your request rate, or use a proxy that changes your IP address regularly.
> 
> There is no real way to bypass this since it's kind of an IP-blocking system they have, to avoid getting scrapped.

Okay, thanks.
