### ISSUE TITLE
Only works on local host

### ISSUE THREAD

**Issue by mayconasilva** [EdouardCourty/user-instagram#24]
I'm using the library to create an iscord bot, however I can't find a host that this library works with.

**Comment by EdouardCourty** [comment]
Hello, this problem is well known, the fact is most public hosting services use IP ranges that are being blacklisted.
Instagram surely uses some kind of anti-scrapper, cloudflare-like, which makes the use of this module impossible in some cases.

**Comment by Fab-is-insane** [comment]
same issue
