### ISSUE TITLE
UnableToFetchUserDataError

### ISSUE THREAD

**Issue by iGetAlways** [EdouardCourty/user-instagram#26]
I tried to get data of user 'tassakpro'. And i get this error.
> UnableToFetchUserDataError: An error occured while fetching data for user tassakpro. Maybe this user does not exist ?
     at Function.fromUsername (/app/node_modules/user-instagram/src/Exceptions/UnableToFetchUserDataError.js:7:12)
     at /app/node_modules/user-instagram/src/scrape.js:67:43
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)

User exists. https://www.instagram.com/tassakpro/
It's giving error on github. on my pc, it's working. How can i fix that?

**Comment by Benchamxd** [comment]
Me too having this error 😞

**Comment by Benchamxd** [comment]
@iGetAlways me too getting this error.... @EdouardCourty please see and try to solve it as soon as possible

**Comment by MichaelDM** [comment]
Same problem with me!

**Comment by rsemenyshyn** [comment]
same problem here
```
Error: An error occured while fetching data for user edouard_courty. Maybe this user does not exist ?
    at Function.fromUsername (UnableToFetchUserDataError.js:7)
    at scrape.js:67
```

**Comment by EdouardCourty** [comment]
Hello guys, the problem here is you are being rate limited, or IP-banned. I had this problem too and the only thing that fixed it was to wait a bit before sending another request...
It's a pain in the ass, I've been trying everything I could to make the request perfectly human and legit, does not change anything.
Also, using it on a VPS can actually never work, sometimes the IP range used by these servers are already blacklisted and the request fails directly.

**Comment by EdouardCourty** [comment]
In fact I think I could handle this error better and return a clear error message saying the request failed instead of saying the user does not exist. I'll work on this asap !
Thanks for the feedback anyway, it's always a pleasure to have interaction !

**Comment by iGetAlways** [comment]
> In fact I think I could handle this error better and return a clear error message saying the request failed instead of saying the user does not exist. I'll work on this asap !
> Thanks for the feedback anyway, it's always a pleasure to have interaction !

so is there no way to solve this error?

**Comment by rjworks** [comment]
Is there a fix to this?

**Comment by iGetAlways** [comment]
PLEASE FIIIXXXX

**Comment by Dark25** [comment]
User not found, please

**Comment by EdouardCourty** [comment]
Hello guys, there is no way to fix this. Try to send less requests.

**Comment by Benchamxd** [comment]
@EdouardCourty 
Sed.....it's ok sir, we appreciate your work ☺....Thanks for making such a useful library 😄

**Comment by iGetAlways** [comment]
> Try to send less requests.

it doesn't work no matter what i do



> @EdouardCourty
> Sed.....it's ok sir, we appreciate your work ☺....Thanks for making such a useful library 😄

😐
