### ISSUE TITLE
Unable to get user data

### ISSUE THREAD

**Issue by kleberfh** [EdouardCourty/user-instagram#27]
When plugin does it's request to instagram, instagram graph api is returning 302 with no data. This is causing:

`scrape.js:18 Uncaught (in promise) TypeError: Cannot read property 'user' of undefined`

**Comment by EdouardCourty** [comment]
Hello, are you using the last version of the package ?

**Comment by EdouardCourty** [comment]
Hey, I think you're being rate-limited by Instagram.
There is currently no way to avoid this, try to reduce the number of requests you send every hour.
