### ISSUE TITLE
Issue fetching the username

### ISSUE THREAD

**Issue by mat-lo** [EdouardCourty/user-instagram#28]
It was working fine previously, and I didn't change any code.
It could be an issue of IG updating their GQL?
I'm pretty sure the user exists, I also tested with other users.

```
/home/pi/apps/roby/node_modules/user-instagram/src/scrape.js:18
    const user = GQL.data.graphql.user;
                                  ^

TypeError: Cannot read property 'user' of undefined
```

and

```
UnableToFetchUserDataError: An error occured while fetching data for user oio.studio. Maybe this user does not exist ?
    at Function.fromUsername (/Users/ml/www/oio/apps/roby/node_modules/user-instagram/src/Exceptions/UnableToFetchUserDataError.js:7:12)
    at /Users/ml/www/oio/apps/roby/node_modules/user-instagram/src/scrape.js:67:43
```

**Comment by EdouardCourty** [comment]
Hello ! Thanks for submitting this issue.
I'm checking this right now.

**Comment by EdouardCourty** [comment]
The GraphQL Instagram uses has not changed. 
The answer is that you are (sadly) being rate-limited. A lot of people are having the same issue right now, and it's not something that is fixable.

The only way to get able to scrape again is to limit the amount of requests you send. Try to wait for a few hours, of even tomorrow, run your code again and let me know if it works again !
