### ISSUE TITLE
Block instagram 

### ISSUE THREAD

**Issue by EmersonGarrido** [EdouardCourty/user-instagram#29]
Hey man, what resolve the block instagram ?

**Comment by EdouardCourty** [comment]
Hello, can you add some explanation to your question ?

**Comment by EmersonGarrido** [comment]
I use it in my applications to get comments from posts, I have thousands of hits per day, but I get reports of instagram blocks by IP and CORS errors sometimes.

**Comment by EmersonGarrido** [comment]
Error CORS :
has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by EdouardCourty** [comment]
Hello, I never has this error before, let me check if I found anything.

IP blocking issues are normal, everyone experience them when hitting a lot, that's a problem I cannot solve, sadly !

**Comment by EdouardCourty** [comment]
I don't get any CORS issues, if that happens at the same time as the IP blocking, you may just want to wait a bit before hitting again !

**Comment by EmersonGarrido** [comment]
Hey man, test my aplications :
instasorteio.com.br
sorteiogram.com.br

Checked terminal networking.
