### ISSUE TITLE
Show only a few Posts

### ISSUE THREAD

**Issue by UltimatumGamer** [EdouardCourty/user-instagram#3]
> The module only shows a few posts, not all 
> I have 74 and the module only gives me 10

**Comment by Bluebie** [comment]
I'm having the same issue. It doesn't seem to have any code for accessing the pages beyond the first

**Comment by EdouardCourty** [comment]
Hey, I use the GraphQL JSON query that is on the loaded DOM. To access the other post I have to use something like PhantomJS to go further in the webpage and this could slow-down the whole process. I'm working on a way to implement this in the best way possible, I'll update you.

Thanks !

**Comment by Tarek-23** [comment]
Hello, has this issue been addressed? It still fetches the first few (10-12) posts for me and not more.
