### ISSUE TITLE
Basic use of the package

### ISSUE THREAD

**Issue by Ntshembo-Hlongwane1** [EdouardCourty/user-instagram#32]
**I literally have this on my code below:**
```
const IG = require("user-instagram");

IG("sadi.boii")
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  });
```
**But I still get the following error message**
```
UnableToFetchUserDataError: An error occured while fetching data for user sadi.boii. Maybe this user does not exist ?
    at Function.fromUsername (/home/junior/Desktop/DJ-COACH-EWALLET/node_modules/user-instagram/src/Exceptions/UnableToFetchUserDataError.js:7:12)
    at /home/junior/Desktop/DJ-COACH-EWALLET/node_modules/user-instagram/src/scrape.js:67:43
```

**Comment by musawershah1598** [comment]
same error

**Comment by Lukhajek** [comment]
I'm getting this error too.

**Comment by Lukhajek** [comment]
But it's probably just rate limit.

**Comment by viralvaghela** [comment]
because there are some limitations to call URL

**Comment by 47vigen** [comment]
same error

**Comment by asharma991** [comment]
I am also getting the same error.

**Comment by JonathanTheZero** [comment]
The package is probably just not working anymore

**Comment by David-Dorr** [comment]
In the above example, the code will do an axios GET request to this URL...

> https://www.instagram.com/sadi.boii/?__a=1

This URL is meant to return JSON data related to this Insta account. However, if you do curl (with headers) to see what's happening.. 

> curl -i https://www.instagram.com/sadi.boii/?__a=1

You will see a 302 (redirect) response to **location**: https://www.instagram.com/accounts/login/

In short, Instagram might have put a stop to this package. That being said, it did work for a while for me before I got this error also.

**Comment by EdouardCourty** [comment]
Hello, @David-Dorr makes a good point but I can confirm that the package is still working. 
We don't know Instagram's rate limit tho.

There are more than 15 issues on this repo explaining what is discussed right here.
Please check for the existing issues when you open one, the answer to your question may already exist.

Have a good day !
