### ISSUE TITLE
does not find users

### ISSUE THREAD

**Issue by KatrineD3V** [EdouardCourty/user-instagram#34]
`UnableToFetchUserDataError: An error occured while fetching data for user instasamka. Maybe this user does not exist ?`
![IMG_20210716_001107](https://user-images.githubusercontent.com/57178942/125858336-26d18fe1-7f9b-4586-89e5-0ad2a82bf59c.jpg)

**Comment by blueprintChris** [comment]
Same here... Any ideas?

**Comment by igolka97** [comment]
Any additional errors at console may be?
Is request completed successfully?
