### ISSUE TITLE
"Please submit an Issue on Github"

### ISSUE THREAD

**Issue by j0nibaer** [EdouardCourty/user-instagram#36]
Hi, today i started using this NPM and got a weird error. Please help :(

**Error: Unknown error, please submit an issue on GitHub.
    at C:\Users\---\OneDrive\Dokumente\---\Discord\DC Bots\JoniBot v13\node_modules\user-instagram\src\Instagram\Infrastructure\InstagramRepository.js:374:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)**

**The Code:**
 const instagram = require('user-instagram');
        let name = args[0];
        if(!name) return message.channel.send('Enter an account to search for!');
        await instagram.authenticate(process.env.username, process.env.passwort);
        instagram.getUserData(name).then(userData => {
          let embed = new MessageEmbed()
          .setTitle(`**Profile from: ${userData.getUsername()}**`)
        message.channel.send({embeds:[embed]});
    
        })

**Comment by EdouardCourty** [comment]
Hi, can you provide a link to your repository please ?

**Comment by Lioness100** [comment]
@EdouardCourty I'm also encountering this issue. I simply copy and pasted the example from the README. I can confirm my credentials are correct.

**Comment by Fab-is-insane** [comment]
same issue with me, im running my application on heroku
