### ISSUE TITLE
Can running getUserData too often lead to rate limiting the application?

### ISSUE THREAD

**Issue by mtatko** [EdouardCourty/user-instagram#40]
Hi there!

I am using `instagram.getUserData()` function with a node-cron in 5 minutes interval to check for new photos being posted. I have noticed, that using `instagram.authenticate()` too often leads to the application getting rate limited very fast, so I tried bypassing it with only logging in once during app initialization. That little trick solved the problem, however I was wondering if my app could still gate rate limited for scraping user data too often. If so, what is the optimal interval to prevent rate limit?

Thanks in advance for all of your answers!

**Comment by EdouardCourty** [comment]
Hi, logging too many times leads to rate limiting, what I advice you is to log in once and then keep the app running!

I don't know the amount of requests that will lead to the rate-limit tho, can't help on that :/
