### ISSUE TITLE
No session found when running on google cloud platform

### ISSUE THREAD

**Issue by Fab-is-insane** [EdouardCourty/user-instagram#41]
Hey, I have an issue with login process. Whenever I try to authenticate it works perfectly if I run the app on my PC, but I have hosted it on GCP, It says that "No session found, Did you authenticate?". This happens only on GCP and not on local system. I have a windows 10 machine and debian 10 on gcp.
![Screenshot 2022-03-27 163829](https://user-images.githubusercontent.com/68937935/160278703-0cde0dd3-171c-40e2-9c1b-9204a353fe64.png)

**Comment by EdouardCourty** [comment]
Hi, Instagram sometimes refuses requests from cloud providers such as GCP / AWS...
Can't really help it since it's on their side tho.....

**Comment by Fab-is-insane** [comment]
oh ok.

> Hi, Instagram sometimes refuses requests from cloud providers such as GCP / AWS... Can't really help it since it's on their side tho.....
