### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by exsandebest** [EdouardCourty/user-instagram#5]
![image](https://user-images.githubusercontent.com/51285775/78389057-bd7b6880-75ea-11ea-93a5-a5b6c6cc79d6.png)
It happens sometimes, I think, that something wrong with response from instagram.com

**Comment by EdouardCourty** [comment]
Hey, I updated the code and the way I get the data from Instagram, I don't use cheerio anymore for performance issues.
Make sure to update the module, the data structure should be the same.
In addition the posts with more than one pictures are handled.

**Comment by EdouardCourty** [comment]
Can you show me your code so I can check if something is wrong ?

**Comment by exsandebest** [comment]
I have updated the package now and hope that there will be no more similar errors.
I saved a response from Instagram when this error occurred
[response.txt](https://github.com/EdouardCourty/user-instagram/files/4448743/response.txt)
But since then this error has not occurred again.
I think it could have been a problem with Instagram.

**Comment by EdouardCourty** [comment]
Thanks for providing a log ! I checked the your response and there is actually no informations about the account your provided. Now the module is getting the information by doing something else than just scrapping the page. Make sure to check the username you provided !
It maybe is an Instagram-side problem as well.
