### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by magician11** [EdouardCourty/user-instagram#9]
Is it possible to scrape the comments for a user's media post too?

**Comment by EdouardCourty** [comment]
Hello, sorry for not responding, I was away for a few days, I'm working this around.

**Comment by EdouardCourty** [comment]
I added a method in the module that fetches info about a post such as comments, likes, and other meta-data you may like to have access to. Let me know if you encounter any issues !

**Comment by magician11** [comment]
@EdouardCourty thanks for the update. I can't seem to get it working though.

Can you give a working example here?

**Comment by EdouardCourty** [comment]
Hey, just read the ReadMe and you'll find out ! Use the getPostData method, the comments are listed here.
